spring:
  application:
    name: taskmanagement2
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true